### ISSUE TITLE
Is a hotdog a sandwich?

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/project-ideas#2]
## The problem we're solving

The age old question
### How, when, where, and why does it happen?

Pretty much any time I start to think about it
#### The subject/field/industry where the problem occurs

Mostly the food industry, but occasionally all industries (ie. company cookouts)
## What needs to change?

Really I'd say the clarity on it. Maybe an official decree from big hotdog.
#### The goal of the project

I mean, I'm good with just eating hotdogs for a while until we figure it out.
## Available data sources

http://lib.stat.cmu.edu/DASL/Datafiles/Hotdogs.html
#### Examples of solutions to this problem
- "Yes"
- "No"
#### What does success look like?

![zr4fae5](https://cloud.githubusercontent.com/assets/761444/13556737/30c2d7d8-e3af-11e5-9822-84e7d32f2e81.jpg)

**Comment by flibbertigibbet** [comment]
:hamburger:

**Comment by AcriCAA** [comment]
Yes and my peanut butter banana dog proves it!
